#version: poco-1.10.1-release
#

init:
    - set version=1.10.1
    - set version_tag=poco-%version%-release
image:
  - Visual Studio 2017

platform:
  - x64
  #- x86

configuration:
  - Release
  #- Debug

init:
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" =="Visual Studio 2015" ( set generator=Visual Studio 14 2015)
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" =="Visual Studio 2017" ( set generator=Visual Studio 15 2017)
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" =="Visual Studio 2019" ( set generator=Visual Studio 16 2019)


#install:
  #- cinst cmake
  #

before_build:
  - git clone https://github.com/pocoproject/poco.git
  - cd poco
  - git checkout %version_tag%
  - cd ..


build_script:
  - set
  #- set PATH=C:\Program Files\CMake\bin;C:\ProgramData\chocolatey\bin;%PATH%
  - cmake --version
  - cmake -Hpoco -Bpoco-x64-release.build -G "%generator% Win64" -DENABLE_NETSSL=OFF -DENABLE_CRYPTO=OFF -DENABLE_JWT=OFF -DENABLE_DATA_ODBC=OFF -DENABLE_DATA_MYSQL=OFF -DENABLE_DATA_POSTGRESQL=OFF
  - cmake -Hpoco -Bpoco-x86-release.build -G "%generator%" -DENABLE_NETSSL=OFF -DENABLE_CRYPTO=OFF -DENABLE_JWT=OFF -DENABLE_DATA_ODBC=OFF -DENABLE_DATA_MYSQL=OFF -DENABLE_DATA_POSTGRESQL=OFF
  #- cmake --build poco.build 
  #

after_build:
  - dir/s poco-x64-release.build
  - 7z a poco-appveyor-%version_tag%-x64-release.zip poco-x64-release.build
  - 7z l poco-appveyor-%version_tag%-x64-release.zip
  - 7z a poco-appveyor-%version_tag%-x86-release.zip poco-x86-release.build
  - 7z l poco-appveyor-%version_tag%-x86-release.zip

artifacts:
    - path: '**\*.zip'


