version: poco-1.10.2-release

install:
  - cinst cmake

before_build:
  - git clone https://github.com/pocoproject/poco.git
  - cd poco
  - git checkout %version%


build_script:
  - set PATH=C:\Program Files\CMake\bin;C:\ProgramData\chocolatey\bin;%PATH%
  - cmake -H. -Bcmake-build -DENABLE_NETSSL=OFF -DENABLE_CRYPTO=OFF -DENABLE_JWT=OFF -DENABLE_DATA_ODBC=OFF -DENABLE_DATA_MYSQL=OFF -DENABLE_DATA_POSTGRESQL=OFF
  #- cmake --build cmake-build
