#version: poco-1.10.1-release
#

init:
    - set version=1.10.1
    - set version_tag=poco-%version%-release
image:
  - Visual Studio 2017

platform:
  - x64
  #- x86

configuration:
  - Release
  #- Debug


#install:
  #- cinst cmake

before_build:
  - git clone https://github.com/pocoproject/poco.git
  - cd poco
  - git checkout %version-tag%


build_script:
  - set
  #- set PATH=C:\Program Files\CMake\bin;C:\ProgramData\chocolatey\bin;%PATH%
  - cmake --version
  - cmake -H. -Bcmake-build -DENABLE_NETSSL=OFF -DENABLE_CRYPTO=OFF -DENABLE_JWT=OFF -DENABLE_DATA_ODBC=OFF -DENABLE_DATA_MYSQL=OFF -DENABLE_DATA_POSTGRESQL=OFF
  #- cmake --build cmake-build
