#version: poco-1.10.1-release
#
#

environment:
  # don't use this password if you clone this project as it is encrypted, you should
  # use your owned encrypted password
  APPVEYOR_RDP_PASSWORD:
    secure: iAt3RbMOcprhUGAV1rABgw==


init:
  - set version=1.10.1
  - set version_tag=poco-%version%-release
  - set cmake_flags=-DBUILD_SHARED_LIBS=OFF -DENABLE_NETSSL=OFF -DENABLE_CRYPTO=OFF -DENABLE_JWT=OFF -DENABLE_DATA_ODBC=OFF -DENABLE_DATA_MYSQL=OFF -DENABLE_DATA_POSTGRESQL=OFF

  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" =="Visual Studio 2015" ( set generator=Visual Studio 14 2015& set tver=v140)
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" =="Visual Studio 2017" ( set generator=Visual Studio 15 2017& set tver=v141)
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" =="Visual Studio 2019" ( set generator=Visual Studio 16 2019& set tver=v142)

  - set generator64=%generator% Win64


  #- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

image:
  - Visual Studio 2017

platform:
  - x64
  #- x86 # no need

configuration:
  - Release
  #- Debug # no need



#install:
  #- cinst cmake # no need, use the stock version
  #

before_build:
    - git clone https://github.com/pocoproject/poco.git
    - cd poco
    - git checkout %version_tag%
    - cd ..



build_script:
  - set
  - cmake --version

  - echo.
  - echo *********************************************
  - echo *                                           *
  - echo * Building x64 release                      *
  - echo *                                           *
  - echo *********************************************
  - set arch=x64&set config=release&set build_type=Release&set gen=%generator64%
  - echo cmake -Hpoco -Bpoco-%arch%-%config%.build -G "%gen%" -DCMAKE_BUILD_TYPE=%build_type% -DCMAKE_INSTALL_PREFIX=poco-%arch%-%config%/usr/lib/poco/%version%/%tver%/%arch%/%config% %cmake_flags%
  - echo cmake --build   poco-%arch%-%config%.build --config %build_type%
  - echo cmake --install poco-%arch%-%config%.build --config %build_type%

  - echo.
  - echo *********************************************
  - echo *                                           *
  - echo * Building x64 debug                        *
  - echo *                                           *
  - echo *********************************************
  - set arch=x64&set config=debug&set build_type=Debug&set gen=%generator64%
  - echo cmake -Hpoco -Bpoco-%arch%-%config%.build -G "%gen%" -DCMAKE_BUILD_TYPE=%build_type% -DCMAKE_INSTALL_PREFIX=poco-%arch%-%config%/usr/lib/poco/%version%/%tver%/%arch%/%config% %cmake_flags%
  - echo cmake --build   poco-%arch%-%config%.build --config %build_type%
  - echo cmake --install poco-%arch%-%config%.build --config %build_type%

  - echo.
  - echo *********************************************
  - echo *                                           *
  - echo * Building x86 release                      *
  - echo *                                           *
  - echo *********************************************
  - set arch=x86&set config=release&set build_type=Release&set gen=%generator%
  - echo cmake -Hpoco -Bpoco-%arch%-%config%.build -G "%gen%" -DCMAKE_BUILD_TYPE=%build_type% -DCMAKE_INSTALL_PREFIX=poco-%arch%-%config%/usr/lib/poco/%version%/%tver%/%arch%/%config% %cmake_flags%
  - echo cmake --build   poco-%arch%-%config%.build --config %build_type%
  - echo cmake --install poco-%arch%-%config%.build --config %build_type%

  - echo.
  - echo *********************************************
  - echo *                                           *
  - echo * Building x86 debug                        *
  - echo *                                           *
  - echo *********************************************
  - set arch=x86&set config=debug&set build_type=Debug&set gen=%generator%
  - cmake -Hpoco -Bpoco-%arch%-%config%.build -G "%gen%" -DCMAKE_BUILD_TYPE=%build_type% -DCMAKE_INSTALL_PREFIX=poco-%arch%-%config%/usr/lib/poco/%version%/%tver%/%arch%/%config% %cmake_flags%
  - cmake --build   poco-%arch%-%config%.build --config %build_type%
  - cmake --install poco-%arch%-%config%.build --config %build_type%







  

after_build:
    ##### x64 release #####
    ##- dir/s poco-x64-release.build
    ##- 7z a poco-appveyor-%version%-x64-release.zip    poco-x64-release
    ##- 7z a poco-appveyor-%version%-x64-release-build.zip poco-x64-release.build

    ##### x64 debug   #####
    ##- dir/s poco-x64-debug.build
    ##- 7z a poco-appveyor-%version%-x64-debug.zip    poco-x64-debug
    ##- 7z a poco-appveyor-%version%-x64-debug-build.zip poco-x64-debug.build

    ##### x86 release #####
    ##- dir/s poco-x86-release.build
    ##- 7z a poco-appveyor-%version%-x86-release.zip    poco-x86-release
    ##- 7z a poco-appveyor-%version%-x86-release-build.zip poco-x86-release.build

    ##### x86 debug   #####
    - dir/s poco-x86-debug.build
    - 7z a poco-appveyor-%version%-x86-debug.zip    poco-x86-debug
    - 7z a poco-appveyor-%version%-x86-debug-build.zip poco-x86-debug.build



test_script:
    ##- cmake --install poco-x64-release.build

    ##- dir/s 
    ##- 7z a poco-appveyor-%version%-x64-release.zip    poco-x64-release

artifacts:
    - path: '**\poco-appveyor-*.zip'

on_finish:
    #- endlocal
    #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

